export const schoolList = [
  'Abilene Christian University',
  'Akron',
  'Alabama',
  'Alabama A&M University',
  'Alabama Birmingham',
  'Alabama State University',
  'Albany',
  'Alcorn State University',
  'American University',
  'Appalachian State University',
  'Arizona',
  'Arizona State University',
  'Arkansas Fayetteville',
  'Arkansas Little Rock',
  'Arkansas Pine Bluff',
  'Arkansas State University',
  'Auburn University',
  'Austin Peay State University',
  'Ball State University',
  'Baylor University',
  'Belmont University',
  'Bethune-Cookman University',
  'Binghamton University',
  'Boise State University',
  'Boston College',
  'Boston University',
  'Bowling Green State University',
  'Bradley University',
  'Brigham Young University',
  'Brown University',
  'Bryant University',
  'Bucknell University',
  'Buffalo',
  'Butler University',
  'California Berkeley',
  'California Davis',
  'California Irvine',
  'California Los Angeles',
  'California Polytechnic State University',
  'California Riverside',
  'California Santa Barbara',
  'California State University Bakersfield',
  'California State University Fresno',
  'California State University Fullerton',
  'California State University Northridge',
  'California State University Sacramento',
  'Campbell University',
  'Canisius College',
  'Central Arkansas',
  'Central Connecticut State University',
  'Central Florida',
  'Central Michigan University',
  'Charleston Southern University',
  'Chicago State University',
  'Cincinnati',
  'Citadel',
  'Clemson University',
  'Cleveland State University',
  'Coastal Carolina University',
  'Colgate University',
  'College of Charleston (South Carolina)',
  'College of the Holy Cross',
  'College of William and Mary',
  'Colorado Boulder',
  'Colorado State University',
  'Columbia University-Barnard College',
  'Connecticut',
  'Coppin State University',
  'Cornell University',
  'Creighton University',
  'Dartmouth College',
  'Davidson College',
  'Dayton',
  'Delaware',
  'Delaware State University',
  'Denver',
  'DePaul University',
  'Detroit Mercy',
  'Drake University',
  'Drexel University',
  'Duke University',
  'Duquesne University',
  'East Carolina University',
  'East Tennessee State University',
  'Eastern Illinois University',
  'Eastern Kentucky University',
  'Eastern Michigan University',
  'Eastern Washington University',
  'Elon University',
  'Evansville',
  'Fairfield University',
  'Fairleigh Dickinson University',
  'Florida',
  'Florida A&M University',
  'Florida Atlantic University',
  'Florida Gulf Coast University',
  'Florida International University',
  'Florida State University',
  'Fordham University',
  'Furman University',
  'Gardner-Webb University',
  'George Mason University',
  'George Washington University',
  'Georgetown University',
  'Georgia',
  'Georgia Institute of Technology',
  'Georgia Southern University',
  'Georgia State University',
  'Gonzaga University',
  'Grambling State University',
  'Grand Canyon University',
  'Hampton University',
  'Harvard University',
  'Hawaii Manoa',
  'High Point University',
  'Hofstra University',
  'Houston',
  'Houston Baptist University',
  'Howard University',
  'Idaho',
  'Idaho State University',
  'Illinois Chicago',
  'Illinois State University',
  'Illinois Urbana-Champaign',
  'Incarnate Word',
  'Indiana State University',
  'Indiana University Bloomington',
  'Indiana University-Purdue University Fort Wayne',
  'Iona College',
  'Iowa',
  'Iowa State University',
  'IUPUI',
  'Jackson State University',
  'Jacksonville State University',
  'Jacksonville University',
  'James Madison University',
  'Kansas',
  'Kansas State University',
  'Kennesaw State University',
  'Kent State University',
  'Kentucky',
  'La Salle University',
  'Lafayette College',
  'Lamar University',
  'Lehigh University',
  'Liberty University',
  'Lipscomb University',
  'Long Beach State University',
  'Long Island University-Brooklyn Campus',
  'Longwood University',
  'Louisiana Lafayette',
  'Louisiana Monroe',
  'Louisiana State University',
  'Louisiana Tech University',
  'Louisville',
  'Loyola Marymount University',
  'Loyola University Chicago',
  'Loyola University Maryland',
  'Maine',
  'Manhattan College',
  'Marist College',
  'Marquette University',
  'Marshall University',
  'Maryland Baltimore County',
  'Maryland College Park',
  'Maryland Eastern Shore',
  'Massachusetts Amherst',
  'Massachusetts Lowell',
  'McNeese State University',
  'Memphis',
  'Mercer University',
  'Miami (Florida)',
  'Miami University (Ohio)',
  'Michigan',
  'Michigan State University',
  'Middle Tennessee State University',
  'Minnesota Twin Cities',
  'Mississippi',
  'Mississippi State University',
  'Mississippi Valley State University',
  'Missouri Columbia',
  'Missouri State University',
  'Missouri-Kansas City',
  'Monmouth University',
  'Montana',
  'Montana State University-Bozeman',
  'Morehead State University',
  'Morgan State University',
  'Mount St. Mary’s University',
  'Murray State University',
  'Nebraska Lincoln',
  'Nebraska Omaha',
  'Nevada Reno',
  'New Hampshire',
  'New Jersey Institute of Technology',
  'New Mexico',
  'New Mexico State University',
  'New Orleans',
  'Niagara University',
  'Nicholls State University',
  'Norfolk State University',
  'North Carolina A&T State University',
  'North Carolina Central University',
  'North Carolina Chapel Hill',
  'North Carolina Charlotte',
  'North Carolina Greensboro',
  'North Carolina State University',
  'North Carolina Wilmington',
  'North Carolina-Asheville',
  'North Dakota',
  'North Dakota State University',
  'North Florida',
  'North Texas',
  'Northeastern University',
  'Northern Arizona University',
  'Northern Colorado',
  'Northern Illinois University',
  'Northern Iowa',
  'Northern Kentucky University',
  'Northwestern State University',
  'Northwestern University',
  'Notre Dame',
  'Oakland University',
  'Ohio State University',
  'Ohio University',
  'Oklahoma',
  'Oklahoma State University',
  'Old Dominion University',
  'Oral Roberts University',
  'Oregon',
  'Oregon State University',
  'Pacific',
  'Pennsylvania',
  'Pennsylvania State University',
  'Pepperdine University',
  'Pittsburgh',
  'Portland',
  'Portland State University',
  'Prairie View A&M University',
  'Presbyterian College',
  'Princeton University',
  'Providence College',
  'Purdue University',
  'Quinnipiac University',
  'Radford University',
  'Rhode Island',
  'Rice University',
  'Richmond',
  'Rider University',
  'Robert Morris University',
  'Rutgers',
  'Sacred Heart University',
  'Saint Francis University (Pennsylvania)',
  'Saint Joseph’s University',
  'Saint Louis University',
  "Saint Mary's College of California",
  'Saint Peter’s University',
  'Sam Houston State University',
  'Samford University',
  'San Diego',
  'San Diego State University',
  'San Francisco',
  'San Jose State University',
  'Santa Clara University',
  'Savannah State University',
  'Seattle University',
  'Seton Hall University',
  'Siena College',
  'South Alabama',
  'South Carolina Columbia',
  'South Carolina State University',
  'South Carolina Upstate',
  'South Dakota',
  'South Dakota State University',
  'South Florida',
  'Southeast Missouri State University',
  'Southeastern Louisiana University',
  'Southern California',
  'Southern Illinois University Carbondale',
  'Southern Illinois University Edwardsville',
  'Southern Methodist University',
  'Southern Mississippi',
  'Southern University Baton Rouge',
  'Southern Utah University',
  'St. Bonaventure University',
  'St. Francis College Brooklyn',
  'St. John’s University (New York)',
  'Stanford University',
  'Stephen F. Austin State University',
  'Stetson University',
  'Stony Brook University',
  'Syracuse University',
  'Temple University',
  'Tennessee Chattanooga',
  'Tennessee Knoxville',
  'Tennessee Martin',
  'Tennessee State University',
  'Tennessee Technological University',
  'Texas A&M University College Station',
  'Texas A&M University-Corpus Christi',
  'Texas Arlington',
  'Texas Austin',
  'Texas Christian University',
  'Texas El Paso',
  'Texas Rio Grande Valley',
  'Texas San Antonio',
  'Texas Southern University',
  'Texas State University',
  'Texas Tech University',
  'Toledo',
  'Towson University',
  'Troy University',
  'Tulane University',
  'Tulsa',
  'U.S. Air Force Academy',
  'U.S. Military Academy',
  'U.S. Naval Academy',
  'UNLV',
  'Utah',
  'Utah State University',
  'Utah Valley University',
  'Valparaiso University',
  'Vanderbilt University',
  'Vermont',
  'Villanova University',
  'Virginia',
  'Virginia Commonwealth University',
  'Virginia Military Institute',
  'Virginia Polytechnic Institute and State University',
  'Wagner College',
  'Wake Forest University',
  'Washington',
  'Washington State University',
  'Weber State University',
  'West Virginia University',
  'Western Carolina University',
  'Western Illinois University',
  'Western Kentucky University',
  'Western Michigan University',
  'Wichita State University',
  'Winthrop University',
  'Wisconsin Madison',
  'Wisconsin Milwaukee',
  'Wisconsin-Green Bay',
  'Wofford College',
  'Wright State University',
  'Wyoming',
  'Xavier University',
  'Yale University',
  'Youngstown State University'
]
